name = "ical-sync-production"
main = "worker_index_resolved.js"
compatibility_date = "2026-07-06"

[env.production]
name = "ical-sync-production"
main = "worker_index_resolved.js"
compatibility_date = "2026-07-06"

[[env.production.triggers.crons]]
cron = "* * * * *"

[env.production.vars]
SUPABASE_URL = "https://mzrnwtwyuligsaxeoxhh.supabase.co"

[env.production.secrets]
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_WWfq_hzwGiBS7BfZLQ9uyA_o_Znm1qA"
